travis:
  secure:
    BINSTAR_TOKEN: R9iBkdbiJp1+HXAZj5xtAuMs1l5OAAW1b85KzvcXuJfFFssN4PA4ykpF+Eb67dt4X5OHN3FeMFwQ28v8dDdRrRCjeAb82c7AN1eCgVjsRU/ax5KOVJC0S8eKtaJN7HAXIPys5RtHwHKLdfv4vbICBCsEBPt5uyGFkT1M0zIXOs/ujTJlrzCoRvU59b+T29v3j3VQtp4tKlAKdnlAJiRr0KhGCCBTn3Z0cbi+6Y7YzUwp+QZZh13K4mQBrFw5+gzHE0XK3cVrwww3y0RxbBsTf2cVcrK3hvPGpv7dyhCdIG2nERNOUmrwGoiFg8s6RfXApU+567UIVBh7FRPrqAS+l63W2RyUJ44tkWIqp+ViWr2Eq9PpssM+A6mnwmkESQvRra8IcDJO56coy5a5CTF/ayBbFluzfiXwUicqLfrFMbrE4wC7XTuMJmHeBsV+pFFfDObYmRFb6ETWqFYvqfgofZEaN8Dg+A7SlcjX8M1EoqgtWAD6lNiekTvyIK1Efta1TSv+L7nwhZCHW4Giw45pqM/GccerkfVG9/KxedXzzLr7VimaidkOiG/bXX0TRxcOgK1ykcn2wavIe09O8VHF9vBVzzN7EETu8lopK+ol/HOJcIXqN7BlBS4UvhBDaHJZ6oufoZRP3Z94i6ze/enAp1kdzfZDz4KLbEgMyGIB77Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
